### ISSUE TITLE
the password for the rar

### ISSUE THREAD

**Issue by BurntDog** [SaherBlueEagle/XPR-2020-Free#2]
where do I find rar password?

**Comment by SaherBlueEagle** [comment]
> 
> 
> where do I find rar password?

Check the rar comment , and read the instructions and terms of use carefully please ,please again read the rar comment point by point , YOU WILL FIND THE RAR PASSWORD There
this is very important than the program itself , as also use program in some constraints which are mentioned in README , otherwise it will be your responsibility
Thanks for support and attention
